### PR TITLE
add screenshot to cheatsheet

### PR DESCRIPTION
**Pull request by ottopiramuthu**

### CODE REVIEW

**Comment by Jelmerro** [comment]
Nice, but for some reason the border got removed again...

**Comment by ottopiramuthu** [comment]
The latest commit has added space around the border.

**Comment by Jelmerro** [comment]
Are you sure about that, because I don't see it in the PNG. The reason for this seems to be the same as last time, if you check the [diff](https://github.com/Jelmerro/Vieb/pull/301/files) you can see the dpi and sizes are being changed.

**Comment by ottopiramuthu** [comment]
The spacing has changed again in the latest commit. When I open the png in GIMP, for example, there is space around the text.

**Pull request merged**
