### PR TITLE
add saka key viebrc to help

### PR DESCRIPTION
**Pull request by ottopiramuthu**
Saka key has a bunch of mappings that conflict with Vieb mappings to enter modes. Some of them (e.g. `i`) have alternative default mappings, but others (e.g. `vv`) do not. The list of mappings starts [here](https://key.saka.io/docs/tutorial/basics). Let me know what you want to change.

### CODE REVIEW

**Comment by Jelmerro** [comment]
Looks pretty good, besides the missing mappings to go into insert mode. The Sara key project seems to have [these pass keys](https://key.saka.io/docs/tutorial/pass-keys). The `;` mapping might make sense to map after #57 is implemented, but `:` is problematic as a shortcut for going to insert mode ("shift-;" is how they list it). There is also a problem with `ctrl-x` for leaving insert mode, as that is `Cut` on most systems, so I'm not sure why these common keys for regular functionality are mapped to such different keys. What do you think makes sense as someone who has used Sara Key more than I have?

**Comment by ottopiramuthu** [comment]
Remapping `:` is unacceptable in my view, so I would make the following changes to Saka key's mappings:
- `:` becomes `<A-;>`
- `ctrl-x` becomes `<A-x>`

Alt is already used in some places, and giving passing-related keys a special modifier so they don't conflict with standard shortcuts seems good to me. I don't use passing keys often in any Vim browser, so this small change wouldn't affect me much.

Let me know what you think.

**Comment by Jelmerro** [comment]
That seems like a decent compromise, let's go with that :+1:

**Comment by ottopiramuthu** [comment]
I'd be happy to add these mappings, but I'm not sure how to make mappings in Vieb that act like `:` and `ctrl-x`.. and I'm not sure from the pass key issue how these would be implemented in Vieb. Should I just use insert mode?

**Comment by Jelmerro** [comment]
Yes, that's what is the closest alternative to passthrough mode in Vieb, just add those two mappings and I think it's alright.

**Comment by ottopiramuthu** [comment]
I've added those mappings in the latest commit.

**Comment by Jelmerro** [comment]
Great, thanks!

**Pull request merged**
