### PR TITLE
update cheatsheet with visual mode text mappings

### PR DESCRIPTION
**Pull request by ottopiramuthu**

### CODE REVIEW

**Comment by Jelmerro** [comment]
Really great that you are so fast in updating the cheatsheet, this would have taken me hours (I don't use inkscape often :sweat_smile:).

Should we add `*` to the list as well, maybe on the same line as `ts` and just show both as a mapping for that action?

**Comment by ottopiramuthu** [comment]
Oh believe me, it took me hours when I first started this XD

**Comment by ottopiramuthu** [comment]
I've added `*` in the latest commit.

**Comment by Jelmerro** [comment]
Thanks!

**Pull request merged**
