### PR TITLE
possible fix for #427

### PR DESCRIPTION
**Pull request by KunaPrime**

### CODE REVIEW

**Comment by Jelmerro** [comment]
The idea is that you can open a new tab with the current url while in explore mode, not that it opens a new identical tab. For some reason we end up in normal mode since a few releases, but the intended behavior as per docs is to end up in explore mode with the url filled in.

**Comment by KunaPrime** [comment]
i think that problem is in  `setInterval(() => ACTIONS.setFocusCorrectly(), 500)`  namely when new tab is opened main window is in "empty" state so then url falls back to empty one.  I'm not sure how to circumvent this so i did what seemed to be close enough.  

Also can one emulate behavior that i have implemented here with existing actions?

**Comment by Jelmerro** [comment]
This interval has been there since the inception of Vieb, so I am fairly certain it's not the direct cause, but maybe some contents in `setFocusCorrectly` have recently changed that broke this functionality. And yes, your use case is possible if this bug wouldn't exist, since you could map this action with an additional enter key after it.

**Comment by Jelmerro** [comment]
Given the lack of response, I started to look into this myself, and will commit a fix for this shortly. Thanks for taking the time to make a PR!

**Pull request closed without merging**
